<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>total points over 20</name>
  <uuid>c1ce9687-28e8-476a-8fa5-635f109efd13</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	(the points of driver + 'the fine points computed' ) is at least 20
then
	set decision to true ;
else
	set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
